# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Description of what the lane does'
  lane :custom_lane do
    scan(
      workspace: 'GitHubActionsSample.xcworkspace',
      scheme: 'GitHubActionsSample',
      device: 'iPhone 11'
    )

    # gym(
    #   workspace: 'GitHubActionsSample.xcworkspace',
    #   scheme: 'GitHubActionsSample',
    #   export_method: 'ad-hoc'
    # )

    # firebase_app_distribution(
    #   app: '1:544602332843:ios:99bfaf767d781b67f821ee',
    #   groups: 'sample_group',
    #   release_notes: 'by fastlane',
    #   firebase_cli_path: 'node_modules/.bin/firebase'
    # )
  end
end
