name: distribution

on: [push]

jobs:
  bootstrap:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: pod install
      run: pod install

    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'

    - name: Build
      run: |
        xcodebuild -sdk iphonesimulator \
        -workspace GitHubActionsSample.xcworkspace -scheme GitHubActionsSample \
        -configuration Debug build
